/* eslint-disable @typescript-eslint/no-explicit-any */
import { FormEvent, useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, FileSearch, LayoutDashboard, LogOut, Plus, ShieldCheck } from 'lucide-react'

const API = import.meta.env.VITE_API_URL ?? ''
const token = () => localStorage.getItem('safenestt_token')
async function api(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers); headers.set('Content-Type', 'application/json')
  if (token()) headers.set('Authorization', `Bearer ${token()}`)
  const res = await fetch(`${API}${path}`, { ...options, headers })
  if (!res.ok) throw new Error((await res.json().catch(() => ({}))).detail || 'Request failed')
  return res.json()
}
function Layout({ children }: { children: React.ReactNode }) { const navigate=useNavigate(); return <><aside className="sidebar"><Link className="brand" to="/"><ShieldCheck/> <span>SafeNestT</span></Link><nav><Link to="/"><LayoutDashboard/> Dashboard</Link><Link to="/cases"><FileSearch/> My Cases</Link><Link to="/report"><Plus/> Report Scam</Link></nav><button className="logout" onClick={()=>{localStorage.removeItem('safenestt_token');navigate('/login')}}><LogOut/> Sign out</button></aside><main className="appmain">{children}</main></> }
function Protected({ children }: { children: React.ReactNode }) { return token() ? <Layout>{children}</Layout> : <Navigate to="/login" replace/> }
function Login(){const nav=useNavigate();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('safenestt_token',r.token);nav('/')}catch(x){setError((x as Error).message)}}return <main className="auth"><section className="authcard"><Link className="brand" to="/"><ShieldCheck/> SafeNestT</Link><h1>Welcome back</h1><p>Sign in to your fraud protection workspace.</p>{error&&<div className="error">{error}</div>}<form className="form" onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8}/></label><button className="button primary">Sign in</button></form><p>New to SafeNestT? <Link to="/register">Create an account</Link></p></section></main>}
function Register(){const nav=useNavigate();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const r=await api('/api/auth/register',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('safenestt_token',r.token);nav('/')}catch(x){setError((x as Error).message)}}return <main className="auth"><section className="authcard"><Link className="brand" to="/"><ShieldCheck/> SafeNestT</Link><h1>Create your account</h1><p>Keep your scam reports and evidence organized.</p>{error&&<div className="error">{error}</div>}<form className="form" onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={8}/></label><button className="button primary">Create account</button></form><p>Already registered? <Link to="/login">Sign in</Link></p></section></main>}
function Dashboard(){const[cases,setCases]=useState<any[]>([]);useEffect(()=>{api('/api/cases').then(setCases).catch(()=>{})},[]);return <section className="page"><div className="pagehead"><div><div className="eyebrow">SECURITY WORKSPACE</div><h1>Your SafeNestT dashboard</h1><p>Report fraud, preserve evidence, and track investigation progress.</p></div><Link className="button primary" to="/report">Report a Scam</Link></div><div className="statgrid"><div className="stat"><span>My cases</span><strong>{cases.length}</strong></div><div className="stat"><span>Open cases</span><strong>{cases.filter(c=>c.status==='open').length}</strong></div><div className="stat"><span>Protected</span><strong>Active</strong></div></div><div className="panel"><h2>Recent cases</h2>{cases.slice(0,5).map(c=><Link className="caseRow" key={c.id} to={`/cases/${c.id}`}><span><b>{c.title}</b><small>{c.case_type}</small></span><em>{c.status}</em></Link>)}{!cases.length&&<div className="empty"><AlertTriangle/><h3>No cases yet</h3><p>Start by reporting the scam or fraud incident.</p><Link className="button primary" to="/report">Create your first case</Link></div>}</div></section>}
function Report(){const nav=useNavigate();const[type,setType]=useState('');const[description,setDescription]=useState('');const[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const c=await api('/api/cases',{method:'POST',body:JSON.stringify({case_type:type,description})});nav(`/cases/${c.id}`)}catch(x){setError((x as Error).message)}}return <section className="page narrow"><div className="eyebrow">NEW CASE</div><h1>Report a scam or fraud</h1><p>Start with the facts you know. You can add evidence and request an investigation after creating the case.</p><div className="panel"><form className="form" onSubmit={submit}>{error&&<div className="error">{error}</div>}<label>Case type<select value={type} onChange={e=>setType(e.target.value)} required><option value="">Select a case type</option><option>Online scam</option><option>Crypto fraud</option><option>Identity theft</option><option>Payment fraud</option><option>Investment fraud</option><option>Other</option></select></label><label>What happened?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe what happened, who contacted you, what you paid or lost, and any links or transaction details you have." rows={9} required minLength={10}/></label><button className="button primary">Create Case</button></form></div></section>}
function Cases(){const[cases,setCases]=useState<any[]>([]);useEffect(()=>{api('/api/cases').then(setCases).catch(()=>{})},[]);return <section className="page"><div className="pagehead"><div><div className="eyebrow">YOUR CASES</div><h1>Case Center</h1></div><Link className="button primary" to="/report">New Case</Link></div><div className="panel">{cases.map(c=><Link className="caseRow" key={c.id} to={`/cases/${c.id}`}><span><b>{c.title}</b><small>{c.case_type} · {new Date(c.created_at).toLocaleDateString()}</small></span><em>{c.status}</em></Link>)}{!cases.length&&<div className="empty"><FileSearch/><h3>No cases yet</h3><p>Your reported scams will appear here.</p></div>}</div></section>}
function CaseDetail(){const{id}=useParams();const[data,setData]=useState<any>(null);const[label,setLabel]=useState('');const[content,setContent]=useState('');const[message,setMessage]=useState('');async function load(){setData(await api(`/api/cases/${id}`))}useEffect(()=>{load().catch(e=>setMessage(e.message))},[id]);async function add(e:FormEvent){e.preventDefault();await api(`/api/cases/${id}/evidence`,{method:'POST',body:JSON.stringify({kind:'user_note',label,content})});setLabel('');setContent('');load()}async function investigate(){const r=await api(`/api/cases/${id}/investigate`,{method:'POST'});setMessage(r.summary||r.message);load()}if(!data)return <section className="page"><p>{message||'Loading case…'}</p></section>;return <section className="page"><Link to="/cases">← Back to cases</Link><div className="pagehead"><div><div className="eyebrow">CASE #{data.case.id}</div><h1>{data.case.title}</h1><p>{data.case.description}</p></div><button className="button primary" onClick={investigate}>Start AI Investigation</button></div><div className="detailgrid"><div className="panel"><h2>Evidence</h2>{data.evidence.map((x:any)=><article className="evidence" key={x.id}><b>{x.label}</b><small>{x.kind} · {new Date(x.created_at).toLocaleString()}</small><p>{x.content}</p></article>)}<form className="form" onSubmit={add}><label>Evidence label<input value={label} onChange={e=>setLabel(e.target.value)} required/></label><label>Evidence / notes<textarea value={content} onChange={e=>setContent(e.target.value)} rows={4} required/></label><button className="button secondary">Add Evidence</button></form></div><div className="panel"><h2>Investigation</h2>{message&&<div className="notice">{message}</div>}{data.investigations.map((x:any)=><div className="investigation" key={x.id}><b>Investigation #{x.id}</b><span>{x.status}</span></div>)}{!data.investigations.length&&<p className="muted">No investigation has been started.</p>}<h2>Findings</h2>{data.findings.map((f:any)=><article className="finding" key={f.id}><b>{f.title}</b><small>{f.category} · {f.confidence}</small><p>{f.detail}</p></article>)}</div></div></section>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/report" element={<Protected><Report/></Protected>}/><Route path="/cases" element={<Protected><Cases/></Protected>}/><Route path="/cases/:id" element={<Protected><CaseDetail/></Protected>}/></Routes>}
