/* eslint-disable @typescript-eslint/no-explicit-any */
import { FormEvent, useState } from 'react'

type Transaction = Record<string, string | boolean>
type Subject = Record<string, string>

export default function IC3Intake({ caseId, onSaved }: { caseId: number; onSaved: () => void }) {
  const [affected, setAffected] = useState('yes')
  const [filer, setFiler] = useState({name:'',business_name:'',phone:'',email:''})
  const [complainant, setComplainant] = useState({name:'',age:'',minor:'no',address:'',city:'',county:'',country:'United States',state:'',zip:'',phone:'',email:''})
  const [business, setBusiness] = useState({targeted:'no',name:'',impacted:'no',it_poc:'',other_poc:'',sector:'',subsector:''})
  const [loss, setLoss] = useState({sent:'no',total:'',contacted:'no'})
  const [tx, setTx] = useState<Transaction>({transaction_type:'',other_transaction_type:'',money_sent_or_lost:'no',amount_usd:'',transaction_date:'',contacted_financial_institution:'no',originating_bank_name:'',originating_bank_address:'',originating_bank_city:'',originating_bank_state:'',originating_bank_country:'',originating_bank_zip:'',originating_name_on_account:'',originating_account_number:'',cryptocurrency_type:'',p2p_application:'',transaction_id_hash:'',cryptocurrency_atm:'',prepaid_gift_card_type:'',atm_address:'',originating_wallet_address:'',originating_account_identifier:'',prepaid_gift_card_number:'',recipient_bank_name:'',recipient_bank_address:'',recipient_bank_city:'',recipient_bank_state:'',recipient_bank_country:'',recipient_bank_zip:'',recipient_name_on_account:'',recipient_name:'',recipient_routing_number:'',recipient_account_number:'',recipient_swift_code:'',recipient_wallet_address:'',recipient_account_identifier:'',recipient_identifier:''})
  const [subject, setSubject] = useState<Subject>({name:'',business_name:'',address:'',city:'',country:'',state:'',zip_code:'',phone:'',email:'',website_social_media:'',ip_address:''})
  const [incident, setIncident] = useState('')
  const [technical, setTechnical] = useState('')
  const [witnesses, setWitnesses] = useState('')
  const [otherReports, setOtherReports] = useState('')
  const [previous, setPrevious] = useState('no')
  const [previousId, setPreviousId] = useState('')
  const [signature, setSignature] = useState('')
  const [ack, setAck] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const setObj = (setter: any, key: string, value: string) => setter((v: any) => ({...v,[key]:value}))
  async function submit(e: FormEvent) {
    e.preventDefault(); setError(''); setSaving(true)
    try {
      const token = localStorage.getItem('safenestt_token')
      const payload = {
        affected_person: affected === 'yes', filer_name: filer.name, filer_business_name: filer.business_name, filer_phone: filer.phone, filer_email: filer.email,
        complainant_name: complainant.name, complainant_age: complainant.age ? Number(complainant.age) : null, complainant_minor: complainant.minor === 'yes', complainant_address: complainant.address, complainant_city: complainant.city, complainant_county: complainant.county, complainant_country: complainant.country, complainant_state: complainant.state, complainant_zip: complainant.zip, complainant_phone: complainant.phone, complainant_email: complainant.email,
        business_targeted: business.targeted === 'yes', business_name: business.name, business_operations_impacted: business.impacted === 'yes', business_it_poc: business.it_poc, business_other_poc: business.other_poc, critical_infrastructure_sector: business.sector, critical_infrastructure_subsector: business.subsector,
        sent_or_lost_money: loss.sent === 'yes', total_loss_usd: loss.total ? Number(loss.total) : null,
        transactions: [{...tx, money_sent_or_lost: tx.money_sent_or_lost === 'yes', contacted_financial_institution: tx.contacted_financial_institution === 'yes', amount_usd: tx.amount_usd ? Number(tx.amount_usd) : null}],
        subjects: [subject], incident_description: incident, technical_details: technical, witnesses_or_other_affected: witnesses, other_reports: otherReports, update_to_previous_complaint: previous === 'yes', previous_submission_id: previousId, digital_signature: signature, pii_redaction_acknowledged: ack,
      }
      const res = await fetch(`/api/cases/${caseId}/intake`, {method:'POST', headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}, body:JSON.stringify(payload)})
      if (!res.ok) throw new Error((await res.json().catch(()=>({}))).detail || 'Unable to save intake')
      onSaved()
    } catch (e) { setError((e as Error).message) } finally { setSaving(false) }
  }
  const Field = ({label,k, obj, setter, type='text', min}:{label:string;k:string;obj:any;setter:any;type?:string;min?:string}) => <label>{label}<input type={type} min={min} value={String(obj[k] ?? '')} onChange={e=>setObj(setter,k,e.target.value)} /></label>
  return <form className="form ic3form" onSubmit={submit}>
    <div className="panel"><div className="eyebrow">IC3-ALIGNED INTAKE</div><h2>Who is filing?</h2><label>Were you the person affected?<select value={affected} onChange={e=>setAffected(e.target.value)}><option value="yes">Yes</option><option value="no">No</option></select></label>{affected==='no'&&<div className="detailgrid">{(['name','business_name','phone','email'] as const).map(k=><Field key={k} label={k.replace('_',' ')} k={k} obj={filer} setter={setFiler} type={k==='email'?'email':'text'}/>)}</div>}</div>
    <div className="panel"><h2>Complainant information</h2><div className="detailgrid">{(['name','age','address','city','county','state','zip','phone','email'] as const).map(k=><Field key={k} label={`Complainant ${k.replace('_',' ')}`} k={k} obj={complainant} setter={setComplainant} type={k==='age'?'number':k==='email'?'email':'text'}/>)}</div><label>Country<input value={complainant.country} onChange={e=>setObj(setComplainant,'country',e.target.value)}/></label><label>Is the complainant 17 or younger?<select value={complainant.minor} onChange={e=>setObj(setComplainant,'minor',e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label><p className="muted">Do not enter Social Security numbers or dates of birth.</p></div>
    <div className="panel"><h2>Business information</h2><div className="detailgrid"><label>Business targeted?<select value={business.targeted} onChange={e=>setObj(setBusiness,'targeted',e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label><Field label="Business name" k="name" obj={business} setter={setBusiness}/><label>Operations impacted?<select value={business.impacted} onChange={e=>setObj(setBusiness,'impacted',e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label><Field label="Business IT POC" k="it_poc" obj={business} setter={setBusiness}/><Field label="Other Business POC" k="other_poc" obj={business} setter={setBusiness}/><Field label="Critical infrastructure sector" k="sector" obj={business} setter={setBusiness}/><Field label="Critical infrastructure subsector" k="subsector" obj={business} setter={setBusiness}/></div></div>
    <div className="panel"><h2>Financial transaction(s)</h2><div className="detailgrid"><label>Did you send or lose money?<select value={loss.sent} onChange={e=>setObj(setLoss,'sent',e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label><Field label="Total loss (USD)" k="total" obj={loss} setter={setLoss} type="number" min="0"/><label>Contacted bank/exchange?<select value={loss.contacted} onChange={e=>setObj(setLoss,'contacted',e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label></div><h3>Transaction #1</h3><div className="detailgrid"><label>Transaction type<select value={String(tx.transaction_type)} onChange={e=>setObj(setTx,'transaction_type',e.target.value)}><option value="">Select</option><option>Cash</option><option>Check/Cashier's Check</option><option>Cryptocurrency/Crypto ATM</option><option>Debit Card/Credit Card</option><option>Money Order</option><option>Peer-to-Peer Transfer</option><option>Prepaid/Gift Card</option><option>Wire Transfer</option><option>Other</option></select></label>{['other_transaction_type','amount_usd','transaction_date','originating_bank_name','originating_bank_address','originating_bank_city','originating_bank_state','originating_bank_country','originating_bank_zip','originating_name_on_account','originating_account_number','cryptocurrency_type','p2p_application','transaction_id_hash','cryptocurrency_atm','prepaid_gift_card_type','atm_address','originating_wallet_address','originating_account_identifier','prepaid_gift_card_number','recipient_bank_name','recipient_bank_address','recipient_bank_city','recipient_bank_state','recipient_bank_country','recipient_bank_zip','recipient_name_on_account','recipient_name','recipient_routing_number','recipient_account_number','recipient_swift_code','recipient_wallet_address','recipient_account_identifier','recipient_identifier'].map(k=><Field key={k} label={k.replaceAll('_',' ')} k={k} obj={tx} setter={setTx} type={k==='amount_usd'?'number':k==='transaction_date'?'date':'text'}/>)}</div></div>
    <div className="panel"><h2>Subject information</h2><div className="detailgrid">{Object.keys(subject).map(k=><Field key={k} label={k.replaceAll('_',' ')} k={k} obj={subject} setter={setSubject}/>)}</div></div>
    <div className="panel"><h2>Description of incident</h2><label>What happened in your own words?<textarea value={incident} onChange={e=>setIncident(e.target.value)} rows={8} maxLength={3500} required/></label><label>Technical details (email headers, crypto metadata, hashes, etc.)<textarea value={technical} onChange={e=>setTechnical(e.target.value)} rows={6} maxLength={5000}/></label><label>Witnesses or other persons affected<textarea value={witnesses} onChange={e=>setWitnesses(e.target.value)} rows={3} maxLength={1000}/></label><label>Other reports to law enforcement/government agencies<textarea value={otherReports} onChange={e=>setOtherReports(e.target.value)} rows={3} maxLength={1000}/></label></div>
    <div className="panel"><h2>Previous complaint & signature</h2><label>Update to a previously filed complaint?<select value={previous} onChange={e=>setPrevious(e.target.value)}><option value="no">No</option><option value="yes">Yes</option></select></label>{previous==='yes'&&<label>Previous submission ID<input value={previousId} onChange={e=>setPreviousId(e.target.value)}/></label>}<label>Digital signature (full name)<input value={signature} onChange={e=>setSignature(e.target.value)} required/></label><label className="check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} required/> I confirm I have not entered Social Security numbers or dates of birth.</label>{error&&<div className="error">{error}</div>}<button className="button primary" disabled={saving}>{saving?'Saving intake…':'Save IC3-aligned Intake'}</button></div>
  </form>
}
